// Vue.component('project', {
//   template: `
//     <ul>
//       <li v-for="detail in details">{{ detail }}</li>
//     </ul>
//   `
// })

var app = new Vue({
  el: '#app',
  data: {
    projects: [
      { projectName: "Dulaan Project",
        orgName: "Flagstaff International Relief Effort (FIRE)",
        url: "http://www.fireprojects.org/mongolia/dulaan/",
        image: "imgs/dulaan.jpg",
        description: "Dulaan is the Mongolian word for warm. Warm, well-made clothing can allow a child to go to school or an adult to go to work; restore a sense of dignity; and, in some cases, literally save a life.",
        city: "Ulaanbaatar",
        state: "",
        country: "Mongoloia",
        categories: ["disaster relief", "children", "adults", "fire", "poverty", "international"],
        crafts: ["knitting", "crochet", "sewing", "weaving", "no-sew"],
        items: ["blanket", "hat", "mittens", "scarf", "socks", "sweater"],
        freePattern: false,
        yarnSpec: false
      },
      {
        projectName: "Knots of Love for Baby",
        orgName: "Knots of Love",
        url: "http://www.knotsoflove.org/nicu-blanket-patterns",
        image: "imgs/knots-of-love-baby.jpg",
        description: "Knots of Love donates snuggly, soft blankets to Neonatal Intensive Care Units across the country.",
        city: "Costa Mesa",
        state: "California",
        country: "United States",
        categories: ["babies", "hospitals", "national"],
        crafts: ["knitting", "crochet"],
        items: ["blanket"],
        freePattern: true,
        yarnSpec: false
      },
      {
        projectName: "Knots of Love Chemo Caps",
        orgName: "Knots of Love",
        url: "http://www.knotsoflove.org",
        image: "imgs/knots-of-love.jpg",
        description: "Our mission is to warm the hearts & heads of every patient who loses their hair due to chemo!",
        city: "Costa Mesa",
        state: "California",
        country: "United States",
        categories: ["chemo patients", "hospitals", "children", "adults", "national"],
        crafts: ["knitting", "crochet"],
        items: ["hat"],
        freePattern: true,
        yarnSpec: true
      },
      {
        projectName: "Afghans for Afghans",
        orgName: "Afghans for Afghans",
        url: "http://www.afghansforafghans.org",
        image: "imgs/afghans-for-afghans.jpg",
        description: "Afghans for Afghans is a humanitarian and educational people-to-people project that sends hand-knit and crocheted blankets and sweaters, vests, hats, mittens, and socks to the beleaguered people of Afghanistan.",
        city: "San Francisco",
        state: "California",
        country: "United States",
        categories: ["international", "babies", "children", "adults", "hospitals", "poverty"],
        crafts: ["knitting", "crochet"],
        items: ["hat", "mittens", "socks"],
        freePattern: true,
        yarnSpec: true
      },
      {
        projectName: "Blankets for Canada",
        orgName: "Blankets for Canada Society",
        url: "http://www.blankets4canada.ca/",
        image: "imgs/blankets-for-canada.jpg",
        description: "Blankets for Canada is a non-denominational organization devoted to creating blankets for Canadians who need warmth.",
        city: "",
        state: "",
        country: "Canada",
        categories: ["homeless", "poverty", "adults"],
        crafts: ["knitting", "crochet", "quilting", "national"],
        items: ["blankets"],
        freePattern: true,
        yarnSpec: false
      },
      {
        projectName: "Bonnie Babies",
        orgName: "Bonnie Babies Charity",
        url: "http://www.bonniebabies.co.uk/",
        image: "imgs/bonnie-babies.png",
        description: "Bonnie Babies provides clothing, blankets and burial outfits to families of premature babies throughout the United Kingdom.",
        city: "",
        state: "",
        country: "United Kingdom",
        categories: ["babies", "hospitals", "national"],
        crafts: ["knitting", "crochet", "sewing"],
        items: ["blanket", "booties", "gown", "hat", "sweater"],
        freePattern: true,
        yarnSpec: false
      },
      {
        projectName: "Christmas at Sea",
        orgName: "The Seaman's Church Institue",
        url: "http://seamenschurch.org/christmas-at-sea",
        image: "imgs/christmas-at-sea.jpg",
        description: "For sailors who have to be away from their families at the holidays, the Seaman's Church Institute of New York and New Jersey provides handmade scarves, socks, hats, gloves, vests and more.",
        city: "Port Newark",
        state: "New Jersey",
        country: "United States",
        categories: ["mariners", "adults", "international"],
        crafts: ["knitting", "crochet"],
        items: ["cowl", "hat", "scarf", "slippers", "socks", "vest"],
        freePattern: true,
        yarnSpec: true
      },
      {
        projectName: "Knit for Kids",
        orgName: "World Vision",
        url: "http://www.knitforkids.org/",
        image: "imgs/knit-for-kids.jpg",
        description: "Knit for Kids is a nationwide program that unites thousands of volunteer knitters to fight poverty with our knitting needles.",
        city: "Sewickley",
        state: "Pennsylvania",
        country: "United States",
        categories: ["children", "national"],
        crafts: ["knitting", "crochet"],
        items: ["blanket", "hat", "scarf", "mittens"],
        freePattern: true,
        yarnSpec: false
      },
      {
        projectName: "Knit Your Bit",
        orgName: "National World War II Museum, New Orleans",
        url: "http://www.nationalww2museum.org/learn/knit-your-bit/",
        image: "imgs/knit-your-bit.jpg",
        description: "Knit Your Bit is a program put on by the National World War II Museum in New Orleans to provide hand-knit scarves to veterans of World War II through veterans' hospitals and other organizations.",
        city: "New Orleans",
        state: "Louisiana",
        country: "United States",
        categories: ["veterans", "adults", "hospitals", "national"],
        crafts: ["knitting", "crochet"],
        items: ["scarf"],
        freePattern: true,
        yarnSpec: false
      },
      {
        projectName: "Project Linus",
        orgName: "Project Linus",
        url: "http://www.projectlinus.org/",
        image: "imgs/project-linus.jpg",
        description: "At Project Linus, a non-profit organization, we provide homemade blankets to children in need.",
        city: "Belton",
        state: "Missouri",
        country: "United States",
        categories: ["children", "national"],
        crafts: ["knitting", "crochet", "quilting"],
        items: ["blanket"],
        freePattern: true,
        yarnSpec: false
      },
      {
        projectName: "Warm Up America!",
        orgName: "Warm Up America Foundation",
        url: "http://www.warmupamerica.org/",
        image: "imgs/warm-up-america.jpg",
        description: "Today Warm Up America distributes warm afghans, caps and other items to tens of thousands of people, thanks to the generosity of knitters and crocheters around the country.",
        city: "Carrollton",
        state: "Texas",
        country: "United States",
        categories: ["baby", "child", "adult", "national"],
        crafts: ["knitting", "crochet"],
        items: ["blanket", "hat", "scarf", "clothing"],
        freePattern: false,
        yarnSpec: false
      },
      {
        projectName: "Battersea Dogs & Cats Home",
        orgName: "Battersea Dogs & Cats Home",
        url: "https://www.battersea.org.uk/support-us/other-ways-give/make-or-donate-goods",
        image: "imgs/bettersea1.jpg",
        description: "We take care of over 8,000 dogs and cats every year. There are lots of things our dogs and cats can use, so we're always on the lookout for donations.",
        city: "London",
        state: "",
        country: "England",
        categories: ["cats", "dogs", "animals", "animal shelter"],
        crafts: ["knitting", "crochet"],
        items: ["bandana", "blanket", "toy", "pet bed"],
        freePattern: true,
        yarnSpec: false
      },
      {
        projectName: "Knit a Square",
        orgName: "KAS Care",
        url: "http://www.knit-a-square.com/",
        image: "imgs/knit-a-square.jpg",
        description: "Do you love crocheting and knitting for charity? Make and send 8 inch x 8inch(20cm) squares and help keep a cold orphan warm.",
        city: "Bryanston",
        state: "",
        country: "South Africa",
        categories: ["children", "orphans", "HIV/AIDS"],
        crafts: ["knitting", "crochet"],
        items: ["blanket", "hand warmers", "hat", "square", "sweater", "toy", "vest"],
        freePattern: true,
        yarnSpec: false
      },
      {
        projectName: "Knit for Peace",
        orgName: "Charity Advisory Trust",
        url: "http://www.knitforpeace.org.uk/",
        image: "imgs/knit-for-peace.jpg",
        description: "We now distribute regularly to over 100 outlets, including hospitals, women’s refuges, refugee drop in centres, prisons, community groups, and hospices as well as to developing countries. We send the knitting (and crochet) to where it’s needed.",
        city: "London",
        state: "",
        country: "England",
        categories: ["children", "adults", "refugees", "hospitals", "prisons", "international"],
        crafts: ["knitting", "crochet"],
        items: ["blanket", "hat", "socks", "sweater", "toy"],
        freePattern: true,
        yarnSpec: false
      }
    ]
  },
  methods: {},
  computed: {}
})
